### ISSUE TITLE
how many gpu you used for training?

### ISSUE THREAD

**Issue by liuxiaotong15** [materialsvirtuallab/megnet#71] opened 2019-12-17 14:21 UTC
really a great work, but...

“In our work, we use dedicated GPU resources to train MEGNet models with 100,000 crystals/molecules. It is recommended that you do the same.”

i found tesla p100 12G can’t handle the qm9 training...
and if use cpu mode, 128G memory is not enough.

so I wander how many gpu i need to train a model?

thanks.

**Comment by chc273** [comment] 2019-12-17 14:52
Hmm, the qm9 modes were trained on one gtx 1080Ti.  it should be totally fine. In fact we can train two models on one GPU at the same time. Try reduce megnet blocks and set2set passes.

**Comment by liuxiaotong15** [comment] 2019-12-17 15:00
really thanks for your fast reply.
I used hyperparameters in the readme, and use qm9 for a classification problem.

should I change crystalGraph to something like moleculargraph? Could you please suggest some hyperparameters?

current used:
nfeat_bond = 10
nfeat_global = 2
r_cutoff = 5
gaussian_centers = np.linspace(0, r_cutoff + 1, nfeat_bond)
gaussian_width = 0.5
distance_converter = GaussianDistance(gaussian_centers, gaussian_width)
graph_converter = CrystalGraph(bond_converter=distance_converter, cutoff=r_cutoff)
model = MEGNetModel(nfeat_bond, nfeat_global, 
                    graph_converter=graph_converter)

**Comment by chc273** [comment] 2019-12-17 15:07
https://github.com/materialsvirtuallab/megnet/blob/master/notebooks/qm9_simple_model.ipynb check this example. You may want to reduce the number of megnet blocks to 2.

**Comment by chc273** [comment] 2019-12-17 15:10
Please also check the training parameters, you have likely used a large batch size. We used 128, you can start from 64.

**Comment by liuxiaotong15** [comment] 2019-12-18 01:50
yes, i use nblocks=2, npass=2, batch_size=64, but, qm9 has 134K data, your example only use 80 of it? I found 1000 size datasets is ok, but 134k is too big...

**Comment by liuxiaotong15** [comment] 2019-12-18 02:17
I found there is also a warning in the example:

> /Users/chenchi/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
>   "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

I google it, and find it may produced by tf.gather or tf.nn.embedding_lookup() ?

**Comment by chc273** [comment] 2019-12-18 03:05
If 1000 molecules are ok, then the problem is most likely with your system memory not the GPU.   The GPU stores the model weights and the intermediate data for each batch (not the whole data). If you can train one batch, most likely you can train all. Just try to do a better memory management and del intermediate data. 

Also if somehow you cannot load all data to memory you can also use fit generator of keras that yield batches from loading files on local disk.

**Comment by chc273** [comment] 2019-12-18 03:06
The warning seems to come from tensorflow2.0, I will look into it. Thanks

**Comment by liuxiaotong15** [comment] 2019-12-18 03:36
GPU is not ok even the data size is about 200. I mean 1k data is ok on CPU with 128G memory.
I can load the data successfully, the problem appear when I call model.train...

Anyway, thank you again, megnet is really a nice work.

**Comment by chc273** [comment] 2019-12-18 03:49
Could you please post the error message? Is it a Out-of-memory (OOM) error?

**Comment by chc273** [comment] 2019-12-18 03:51
I dont know if it is somehow associated with the the graph compute part. You may precompute all the graphs (using CPU, in a separate script) and save them. Then in your training script, call `train_from_graphs` method on the graphs.

**Comment by liuxiaotong15** [comment] 2019-12-18 03:57
yes, oom
> > 2019-12-18 11:54:06.216684: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-12GB, Compute Capability 6.0
> > 2019-12-18 11:54:06.218145: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
> > name: Tesla P100-PCIE-12GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
> > pciBusID: 0000:04:00.0
> > 2019-12-18 11:54:06.218287: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> > 2019-12-18 11:54:06.218350: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
> > 2019-12-18 11:54:06.218407: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
> > 2019-12-18 11:54:06.218463: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
> > 2019-12-18 11:54:06.218518: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
> > 2019-12-18 11:54:06.218574: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
> > 2019-12-18 11:54:06.218631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> > 2019-12-18 11:54:06.220801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
> > 2019-12-18 11:54:06.226555: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
> > 2019-12-18 11:54:06.244153: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
> > 2019-12-18 11:54:06.244186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
> > 2019-12-18 11:54:06.244200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
> > 2019-12-18 11:54:06.258412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11312 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-12GB, pci bus id: 0000:04:00.0, compute capability: 6.0)
> > start training
> 
> UserWarning: Conve
> rting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
>   "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
> Epoch 1/10000
> 2019-12-18 11:55:08.661960: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
> 2019-12-18 11:55:19.968393: W tensorflow/core/common_runtime/bfc_allocator.cc:419] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB 
> (rounded to 1157276160).  Current allocation summary follows.
> 2019-12-18 11:55:19.968530: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (256):   Total Chunks: 429, Chunks in use: 428. 107.2KiB alloca
> ted for chunks. 107.0KiB in use in bin. 35.5KiB client-requested in use in bin.
> 2019-12-18 11:55:19.968556: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (512):   Total Chunks: 11, Chunks in use: 11. 5.8KiB allocated 
> for chunks. 5.8KiB in use in bin. 4.6KiB client-requested in use in bin.
> 2019-12-18 11:55:19.968572: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (1024):  Total Chunks: 2, Chunks in use: 1. 3.0KiB allocated fo
> r chunks. 1.2KiB in use in bin. 1.0KiB client-requested in use in bin.
> 2019-12-18 11:55:19.968590: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (2048):  Total Chunks: 27, Chunks in use: 27. 65.2KiB allocated
>  for chunks. 65.2KiB in use in bin. 65.1KiB client-requested in use in bin.
> 2019-12-18 11:55:19.968607: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (4096):  Total Chunks: 17, Chunks in use: 17. 97.5KiB allocated
>  for chunks. 97.5KiB in use in bin. 97.0KiB client-requested in use in bin.
> 2019-12-18 11:55:19.968624: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (8192):  Total Chunks: 90, Chunks in use: 90. 754.0KiB allocate
> d for chunks. 754.0KiB in use in bin. 740.0KiB client-requested in use in bin.
> 
> ...
> 
> File "<string>", line 3, in raise_from
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
>   (0) Resource exhausted:  OOM when allocating tensor with shape[1,30,301374,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by all
> ocator GPU_0_bfc
>          [[node meg_net_layer_1/Tile (defined at /home/inode01/xiaotong/code/megnet_pip/venv_meg/lib/python3.7/site-packages/tensorflow_core/python/fr
> amework/ops.py:1751) ]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation inf
> o.
> 
>          [[meg_net_layer_1/Squeeze_2/_84]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation inf
> o.
> 
>   (1) Resource exhausted:  OOM when allocating tensor with shape[1,30,301374,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by all
> ocator GPU_0_bfc
>          [[node meg_net_layer_1/Tile (defined at /home/inode01/xiaotong/code/megnet_pip/venv_meg/lib/python3.7/site-packages/tensorflow_core/python/fr
> amework/ops.py:1751) ]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_keras_scratch_graph_20049]
> 
> Function call stack:
> keras_scratch_graph -> keras_scratch_graph
> 
>

**Comment by chc273** [comment] 2019-12-18 04:19
Where did you get the molecules? Are those qm9 structures?  Also which tensorflow version are you using? It has to be >=2.0. 

Please do use https://github.com/materialsvirtuallab/megnet/blob/master/notebooks/qm9_simple_model.ipynb  example for correct model training.

**Comment by chc273** [comment] 2019-12-18 04:22
![image](https://user-images.githubusercontent.com/22353204/71055556-f3afdd80-210a-11ea-892c-668ee7dcfbf1.png)

**Comment by liuxiaotong15** [comment] 2019-12-18 05:07
qm9 is a 134K database? i got it from schnet
>>> import tensorflow as tf
>>> tf.__version__
'2.0.0'
>>> import keras
Using TensorFlow backend.
>>> keras.__version__
'2.3.1'
>>>

**Comment by liuxiaotong15** [comment] 2019-12-18 05:19
I think the problem may cause by the training part, not the convertor part. Because when I train the model in each epoch using CPU in 1000 dataset. The machine memory cycle from 10% to 98%. which means 12G to 100G memory usage...

**Comment by chc273** [comment] 2019-12-18 06:24
It seems that you have solved the problem.Closing now.

**Comment by liuxiaotong15** [comment] 2019-12-18 06:26
in fact, no. #72 is a new problem, so I add another one.

**Comment by chc273** [comment] 2019-12-18 06:36
did you run the example? See ny comments before. I cannot reproduce your problem on mac and ubuntu  platform. Please check your data

**Comment by liuxiaotong15** [comment] 2019-12-18 06:38
yes, I can run example. and also small data on a 28 cores CPU with large memory. But for GPU with 12G memory, it crash..

**Comment by liuxiaotong15** [comment] 2019-12-18 06:40
Did you use the 134k qm9 data to train the model?

**Comment by chc273** [comment] 2019-12-18 06:57
Yes, we did remove ~3000 molecules leaving 131k molecules, but the size is about the same. We never encountered such problems. I have run the code from different GPU machines, and no problems.

**Comment by liuxiaotong15** [comment] 2019-12-18 07:05
this is my model. just change label into a length=5 one-hot vector for classification.

> model = MEGNetModel(nfeat_bond, nfeat_global,
>                     nblocks=2,
>                     npass=2, 
>                     graph_converter=graph_converter,
>                     is_classification=True,
>                     ntarget=5)

**Comment by chc273** [comment] 2019-12-19 04:00
I have not tried training multitask classification using megnet before. I dont think I have implemented softmax in the readout layer, so your problem here probably requires new codes. You should start from simple cases and make sure it works. So far, your problem is likely related to the specific data.

**Comment by liuxiaotong15** [comment] 2019-12-19 05:01
yes, i am also strange why no softmax. But there is a 'is_classification' parameter in train(), so I thought Megnet support classification... Maybe I am wrong...

**Comment by chc273** [comment] 2019-12-19 05:43
MEGNET supports classification, by default it solves multi-label and single-label two-class problems, and it does not need softmax. With small code change, it can handle other classification problems. Since there are too many choices, we decide not to make them as default options for now. Please know your problem and understand what you are doing.

**Closed** 2019-12-19 05:44 UTC

**Comment by liuxiaotong15** [comment] 2019-12-19 07:06
Yes, understand. Thank you very much and have a good day.
